extraction:
  cpp:
    after_prepare:
    - "echo $LGTM_WORKSPACE"
    - "echo $LGTM_SRC"
    - "export PPA_DIR=$LGTM_WORKSPACE/ppa"
    - "export PPA_PREFIX=$PPA_DIR/usr"
    - "mkdir -p $PPA_PREFIX"
    - "export PKG_CONFIG_PATH=\"$PPA_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH\""
    - "wget https://launchpad.net/~nugulinux/+archive/ubuntu/sdk/+files/libnugu-epd-dev_2.1.11ubuntu5~bionic_amd64.deb"
    - "wget https://launchpad.net/~nugulinux/+archive/ubuntu/sdk/+files/libnugu-kwd-dev_0.9.38ubuntu6~bionic_amd64.deb"
    - "wget https://launchpad.net/~nugulinux/+archive/ubuntu/sdk/+files/libnugu-epd_2.1.11ubuntu5~bionic_amd64.deb"
    - "wget https://launchpad.net/~nugulinux/+archive/ubuntu/sdk/+files/libnugu-kwd_0.9.38ubuntu6~bionic_amd64.deb"
    - "pwd && ls -l"
    - "ar x libnugu-epd_2.1.11ubuntu5~bionic_amd64.deb"
    - "cd $PPA_DIR && tar xvf $LGTM_SRC/data.tar.xz && cd -"
    - "ar x libnugu-kwd_0.9.38ubuntu6~bionic_amd64.deb"
    - "cd $PPA_DIR && tar xvf $LGTM_SRC/data.tar.xz && cd -"
    - "ar x libnugu-epd-dev_2.1.11ubuntu5~bionic_amd64.deb"
    - "cd $PPA_DIR && tar xvf $LGTM_SRC/data.tar.xz && cd -"
    - "ar x libnugu-kwd-dev_0.9.38ubuntu6~bionic_amd64.deb"
    - "cd $PPA_DIR && tar xvf $LGTM_SRC/data.tar.xz && cd -"
    - "cp -a $PPA_PREFIX/include/nugu-epd/* include/"
    - "cp -a $PPA_PREFIX/include/nugu-kwd/* include/"
    - "ls -l include"
    - "cp -a $PPA_PREFIX/lib/x86_64-linux-gnu/* $PPA_PREFIX/lib/"
    - "ls -lR $PPA_PREFIX/lib"
    - "sed -i 's@^libdir\\=\\/usr\\/lib@libdir\\='\"$PPA_PREFIX\"'/lib@' $PPA_PREFIX/lib/pkgconfig/nugu-epd.pc"
    - "sed -i 's@^libdir\\=\\/usr\\/lib@libdir\\='\"$PPA_PREFIX\"'/lib@' $PPA_PREFIX/lib/pkgconfig/nugu-epd.pc"
